import { z } from "zod";

const slugRegex = /^[a-z0-9]+(-[a-z0-9]+)*$/;

// z.guid() (8-4-4-4-12 hex, no version/variant constraint) rather than
// z.uuid() (strict RFC 4122): the seed data's hand-assigned ids
// (categories, products, etc.) aren't RFC-4122-compliant v4 UUIDs, but
// they're still valid Postgres `uuid` column values — z.uuid() rejected
// them outright.

export const productVariantSchema = z.object({
  id: z.guid().optional(),
  color: z.string().trim().min(1, "Cor obrigatória").max(60),
  color_hex: z
    .string()
    .trim()
    .regex(/^#[0-9a-fA-F]{6}$/, "Use um hex válido, ex: #0A0A0A")
    .optional()
    .or(z.literal("")),
  size: z.string().trim().min(1, "Tamanho obrigatório").max(20),
  // Auto-generated by the form (SLUG-COR-TAMANHO); never persisted empty —
  // see deriveVariants() in lib/variants.ts.
  sku: z.string().trim().min(1, "SKU obrigatório").max(80),
  stock: z.coerce.number().int().min(0, "Estoque não pode ser negativo").default(0),
  // Photo for this specific color — same URL repeated across every size
  // row of that color (colors aren't a first-class table, just a shared
  // value across variant rows).
  image_url: z.url().optional().or(z.literal("")),
});

export const productImageSchema = z.object({
  id: z.guid().optional(),
  url: z.url("URL de imagem inválida"),
  alt: z.string().trim().max(200).optional().or(z.literal("")),
  position: z.coerce.number().int().min(0).default(0),
});

export const productSchema = z
  .object({
    name: z.string().trim().min(2, "Nome muito curto").max(160),
    slug: z
      .string()
      .trim()
      .min(2, "Slug muito curto")
      .max(160)
      .regex(slugRegex, "Use apenas letras minúsculas, números e hífen"),
    short_description: z.string().trim().max(300).optional().or(z.literal("")),
    description: z.string().trim().max(4000).optional().or(z.literal("")),
    video_url: z.url("URL de vídeo inválida").optional().or(z.literal("")),
    tags: z.array(z.string().trim().min(1).max(40)).default([]),
    collection: z.string().trim().max(80).optional().or(z.literal("")),
    shipping_note: z.string().trim().max(300).optional().or(z.literal("")),
    exchange_info: z.string().trim().max(500).optional().or(z.literal("")),
    care_instructions: z.string().trim().max(500).optional().or(z.literal("")),
    // A draft can be saved with no price yet — 0 is the placeholder until
    // it's set. Publishing requires a real price (publishableProductSchema).
    price: z.coerce.number().min(0, "Preço não pode ser negativo").default(0),
    compare_at_price: z.coerce.number().positive().optional().nullable(),
    category_id: z.guid().optional().nullable(),
    brand_id: z.guid().optional().nullable(),
    manufacturer_ref: z.string().trim().max(80).optional().or(z.literal("")),
    attributes: z.record(z.string(), z.string()).optional().nullable(),
    badge: z.enum(["lancamento", "oferta", "mais_vendido"]).optional().nullable(),
    status: z.enum(["draft", "active", "archived"]).default("draft"),
    featured: z.boolean().default(false),
    position: z.coerce.number().int().min(0).default(0),
    images: z.array(productImageSchema).default([]),
    variants: z.array(productVariantSchema).default([]),
  })
  .refine(
    (data) =>
      !data.compare_at_price || data.compare_at_price > data.price,
    {
      message: "O preço 'de' deve ser maior que o preço atual",
      path: ["compare_at_price"],
    },
  );

export type ProductInput = z.infer<typeof productSchema>;
export type ProductVariantInput = z.infer<typeof productVariantSchema>;
export type ProductImageInput = z.infer<typeof productImageSchema>;

// ------------------------------------------------------------------
// Publish gate — a draft can be saved incomplete; flipping status to
// "active" (publishing) must not. Anchors map each failure to a
// section id in the form (ProductForm renders matching `id="..."`
// wrappers) so the "what's missing" list can link straight to it.
// ------------------------------------------------------------------
export const PUBLISH_FIELD_ANCHORS: Record<string, string> = {
  price: "field-price",
  category_id: "field-category",
  description: "field-description",
  images: "field-images",
  variants: "field-variants",
};

export const publishableProductSchema = productSchema.superRefine((data, ctx) => {
  if (!data.price || data.price <= 0) {
    ctx.addIssue({
      code: "custom",
      path: ["price"],
      message: "Defina um preço maior que zero",
    });
  }
  if (!data.category_id) {
    ctx.addIssue({
      code: "custom",
      path: ["category_id"],
      message: "Selecione uma categoria",
    });
  }
  if (!data.description || data.description.trim().length < 30) {
    ctx.addIssue({
      code: "custom",
      path: ["description"],
      message: "Descrição completa precisa de pelo menos 30 caracteres",
    });
  }
  if (data.images.length === 0) {
    ctx.addIssue({
      code: "custom",
      path: ["images"],
      message: "Adicione ao menos 1 imagem",
    });
  }
  if (data.variants.length === 0) {
    ctx.addIssue({
      code: "custom",
      path: ["variants"],
      message: "Adicione ao menos 1 variação (ou marque como produto sem variações)",
    });
  } else if (data.variants.some((v) => !v.color.trim() || !v.size.trim() || !v.sku.trim())) {
    ctx.addIssue({
      code: "custom",
      path: ["variants"],
      message: "Toda variação precisa de cor, tamanho e SKU preenchidos",
    });
  }
});

export type PublishIssue = { anchor: string; message: string };

/**
 * Validates a product for saving; when `status` is "active", also runs
 * the stricter publish gate. Used both client-side (to block the save
 * button and list what's missing) and server-side (defense in depth —
 * see lib/actions/products.ts).
 */
export function collectPublishIssues(data: ProductInput): PublishIssue[] {
  if (data.status !== "active") return [];

  const result = publishableProductSchema.safeParse(data);
  if (result.success) return [];

  const seen = new Set<string>();
  const issues: PublishIssue[] = [];
  for (const issue of result.error.issues) {
    const field = String(issue.path[0] ?? "");
    const anchor = PUBLISH_FIELD_ANCHORS[field];
    if (!anchor || seen.has(issue.message)) continue;
    seen.add(issue.message);
    issues.push({ anchor, message: issue.message });
  }
  return issues;
}
